blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/votrung654/EShelf/discussions
    about: Ask questions or start a discussion about the project






