apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-service-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ml-service=docker.io/22521571/eshelf-ml-service
    argocd-image-updater.argoproj.io/ml-service.update-strategy: digest
    argocd-image-updater.argoproj.io/ml-service.allow-tags-regex: '^dev$'
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/kustomize-image-name: eshelf/ml-service
    argocd-image-updater.argoproj.io/git-commit-user: github-actions[bot]
    argocd-image-updater.argoproj.io/git-commit-email: github-actions[bot]@users.noreply.github.com
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/votrung654/EShelf.git
    targetRevision: main
    path: infrastructure/kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: eshelf-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

